services:
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${SCRAPPER_DB_NAME}
      POSTGRES_USER: ${SCRAPPER_USERNAME}
      POSTGRES_PASSWORD: ${SCRAPPER_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/${SCRAPPER_DB_NAME}
      - --username=${SCRAPPER_USERNAME}
      - --password=${SCRAPPER_PASSWORD}
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }
