app:
  scheduler:
    enable: true
    interval: PT10S
    force-check-delay: PT10S
  link:
    git-hub-uri: "https://api.github.com/repos/"
    stack-overflow-uri: "https://api.stackexchange.com/2.3/questions/"

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
