app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-uri: http://localhost:8080

spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
  application:
    name: bot
  jackson:
    time-zone: UTC

kafka:
  bootstrapServers: localhost:29092
  groupId: bot
  autoOffsetReset: latest
  maxPollIntervalMs: 300_000
  enableAutoCommit: true
  concurrency: 1
  schemaRegistryUrl: 'http://localhost:28081'


bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      strategy: first
      http-response-body: "{ \"code\": 429, \"error\": \"Too Many Requests\", \"description\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 100
              time: 1
              unit: hours

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
